### ISSUE TITLE
Should cluedin-env files be in .gitignore?

### ISSUE THREAD

**Issue by dervalp** [CluedIn-io/Simple-Docker-Deployment#10]
Each time I am using 'Simple-Docker-Deployment', I can push the cluedin-env files.

![image](https://user-images.githubusercontent.com/928792/49425213-31122900-f79d-11e8-835f-0db837e772d9.png)

@rauljmz do you think we should add that in .gitignore?

**Comment by rauljmz** [comment]
Valid point, except I don't think the .gitignore will help. We need them in the repo, but we don't want future changes to them. The only way I know how to do this is to run ```git update-index --assume-unchanged .\cluedin-env.vars .\domains.vars```
