### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by dervalp** [CluedIn-io/Simple-Docker-Deployment#17]
- [once P-R merged ] Should the name CluedIn appears to make sure user understands it is cluedin -> Rename repo to Cluedin-Docker-Local-Deployment
- [x] Maybe worth mentioning you need powershell command in 'admin' mode
- [not needed] My machine was not supporting unix, :

`Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

- [x] I had to update the `1903` to make it work
- [x] Some information to look at to see if I was supporting lcow (docker info)
- [x] Some instruction on how to verify that the app is booting ( docker-compose logs)

**Comment by dervalp** [comment]
- [x] when accessing the app, I had to accept the HTTPS certificate
- [x] the link to the app is wrong (missing https://)

**Comment by dervalp** [comment]
- [x] document how to signup an organization (or provide script) so you can access with default:

`admin@foobar.com` with `foobar23`

**Comment by dervalp** [comment]
- [x] need access to the email (without setup any external tool such as mail trap)

**Comment by rauljmz** [comment]
Will rename repo afterwards when PR is merged
